### ISSUE TITLE
Hashes of DATs incorrect

### ISSUE THREAD

**Issue by 2Col** [Tomasak/GTA-Downgraders#1]
GTA IV CE 1.2.0.59 vanilla
IV-RR-10-08-2024
![ss](https://github.com/user-attachments/assets/5033d43b-2f61-4248-8c95-e24ea7a5300b)

**Comment by Tomasak** [comment]
Indeed, found more issues, but guy helping me with installer can fix tomorrow.

IV fixer should work fine to install the RR mod
https://gtaforums.com/topic/996609-iv-fixer/

**Comment by ColinM9991** [comment]
> IV fixer should work fine to install the RR mod

Not quite. This reports a checksum error too

**Comment by Tomasak** [comment]
both should be fixed. sorry for inconvenience

**Comment by ColinM9991** [comment]
> both should be fixed. sorry for inconvenience

No inconvenience at all. Thank you for resolving this

**Comment by Tomasak** [comment]
so everything works now?

**Comment by ColinM9991** [comment]
All works fine for me now - have finished testing Vladivostok.

Hopefully @2Col can also confirm when they have some time

**Comment by 2Col** [comment]
This downgrader seems to be fine now. Thanks. I haven't tested IVFixer.
