### ISSUE TITLE
radio recovery does not work

### ISSUE THREAD

**Issue by zaeboba** [Tomasak/GTA-Downgraders#5]
I did everything as instructed, when I went into the game the station played completely different music. At first I thought that added some tracks that were in the beta version or from another part, but after sitting in the game for an hour and a half, I did not hear the same tracks - https://youtu.be/Suju9BPs7Zs

**Comment by Tomasak** [comment]
show me your game folder

**Comment by zaeboba** [comment]
S:\games\SteamLibrary\steamapps\common\Grand Theft Auto IV\GTAIV
![изображение](https://github.com/user-attachments/assets/264dda7d-1b7f-4245-9b6c-d241ce4bfce3)

**Comment by Tomasak** [comment]
seems like fusionfix wasn't installed. it's required for this mod to work. https://github.com/ThirteenAG/GTAIV.EFLC.FusionFix/releases/tag/v3.1.1 dl here

**Comment by zaeboba** [comment]
I thought radio was the only thing that didn't need it....

I installed this mod from the link above, how can it help me with the radio? 🤔

**Comment by Tomasak** [comment]
it needs it to load additional gxts and ual which ships with it custom files from update folder

**Comment by zaeboba** [comment]
Like I said, it didn't bring back the old music, I'm still hearing some “clubby” music.

**Comment by Tomasak** [comment]
even when you start a new game? Since when you load a save it always plays the DLC music first aka the eurobeat mix on vladivostok.

**Comment by zaeboba** [comment]
No, that doesn't work. I'll try reinstalling the game.

**Comment by zaeboba** [comment]
1. reinstalled the game
2. start a new game
it worked until the second mission, then the radio changed back to “clubbing”.
I hate it

**Comment by Tomasak** [comment]
oye, whenever you load a game, it starts at dlc songs. you gotta select the split radio option, so you wont get dlc songs in base game, if you mind it so much.

**Comment by zaeboba** [comment]
Can you elaborate? I don't get it.

**Comment by Tomasak** [comment]
when you install the radio restoration mod you select split radios. Now you will have IV songs only in IV and TBOGT and TLAD songs only in TBOGT and TLAD like it was if you purchased games seperately before Complete Edition came out in 2020
here you can see the song list and how it would be seperated https://gta.fandom.com/wiki/Radio_Stations_in_GTA_IV

**Comment by zaeboba** [comment]
I'm sorry, I still don't understand what I need to set up.
I've put in all the choices and I've put in all the 1's. In any case, after starting a new game, I hear a completely different radio after 2 missions, and I do not restart the game or load a save, the last time I did not even save (autosave does not count) and still after 2 missions started to play electric music (apparently from gay tony).
