### ISSUE TITLE
[GPL License] Where is the code?

### ISSUE THREAD

**Issue by rabaimorp** [Tomasak/GTA-Downgraders#7]
Under the gpl license you are obligated to provide the source code. I can't find where.

**Comment by Tomasak** [comment]
https://github.com/Tomasak/GTA-Downgraders/blob/IV-Radio/Installer/IVCERadioRestorer.nsi

**Comment by rabaimorp** [comment]
> https://github.com/Tomasak/GTA-Downgraders/blob/IV-Radio/Installer/IVCERadioRestorer.nsi

That's weird. The Installer folder and even README.md is missing from the main branch, so and I didn't care to check other ones because its not really common practice to have the LICENSE only and nothing else in the main branch if the code is available.

**Comment by ICantReadYourMind** [comment]
dont make issues if you wont bother to check the branches of the repo or check anything beforehand

**Comment by rabaimorp** [comment]
> dont make issues if you wont bother to check the branches of the repo or check anything beforehand

This is the first repo I've ever seen do this (have nothing but the license in main) so excuse me.
