### ISSUE TITLE
Virustotal "SecureAge Malicious"

### ISSUE THREAD

**Issue by rabaimorp** [Tomasak/GTA-Downgraders#8]
I scanned the .exe using virustotal and "SecureAge" flagged it as "Malicious" if its a false positive it probably should get fixed

**Comment by Tomasak** [comment]
1 AV out of 76 flagged it as virus? The horror!

**Comment by rabaimorp** [comment]
> 1 AV out of 76 flagged it as virus? The horror!

Yes. 0 out of 76 would be optimal.
